## Ejercicio 1: Verificar la edad para entrar en una fiesta
**Descripción:** El programa debe solicitar al usuario su edad y, en función de la misma, mostrar un mensaje indicando si puede entrar a una fiesta. Las reglas son las siguientes:

* Si el usuario tiene menos de 18 años, se mostrará un mensaje diciendo que no puede entrar.
* Si el usuario tiene entre 18 y 25 años (inclusive), se le permitirá entrar con una bebida sin alcohol.
* Si el usuario tiene más de 25 años, se le permitirá entrar con una bebida alcohólica.

**Objetivo**

* Repasar cómo tomar input del usuario.
* Usar condicionales para determinar la salida.
* Mostrar mensajes usando output.

**Tareas:**

1. Tengo que generar un mecanismo por el cual pueda ingresar un valor
2. Asignar el valor ingresado a una variable y ser capaz de identificar cuál de las 3 condiciones se cumple
3. Entregar como output el valor correspondiente a la condición cumplida

In [2]:
# Pedir la edad al usuario
edad = input("Por favor, introduce tu edad: ")
if type(edad) == str:
    edad = int(edad)

# Condicionales para verificar la edad y mostrar el mensaje adecuado
if edad < 0:
    print("ingresaste un valor negativo, esto es incorrecto")
elif 0 <= edad < 18:
    print("Lo siento, no puedes entrar a la fiesta.")
elif 18 <= edad <= 25:
    print("Puedes entrar a la fiesta, pero solo con una bebida sin alcohol.")
elif 25 < edad < 140:
    print("Puedes entrar a la fiesta y te ofrecemos una bebida alcohólica.")
else:
    print("ingresaste un valor mayor que 140, esto es incorrecto")


Lo siento, no puedes entrar a la fiesta.


### Solución Propuesta para el Ejercicio 1

1. Pedir al usuario que ingrese su edad.

2. Intentar convertir la entrada del usuario a un número entero.

3. Capturar la excepción si el valor ingresado no es un número válido.

4. Mostrar un mensaje de error si el usuario no ingresa un número.

5. Verificar si la edad ingresada es menor que 0.

6. Mostrar un mensaje si la edad ingresada es negativa.

7. Verificar si la edad está entre 0 y 18 años.

8. Mostrar un mensaje indicando que no puede asistir a la fiesta si es menor de 18.

9. Verificar si la edad está entre 18 y 25 años.

10. Mostrar un mensaje permitiendo la entrada solo con bebidas sin alcohol si está en este rango.

11. Verificar si la edad está entre 26 y 120 años.

12. Mostrar un mensaje permitiendo la entrada con bebidas alcohólicas si está en este rango.

13. Verificar si la edad es mayor a 120 años.

14. Mostrar un mensaje indicando que la edad ingresada es irrelevante o incorrecta.

In [ ]:
# Pedir la edad al usuario

'''
Aquí podría usarse try-except para intentar 
convertir el valor ingresado a un número entero.

En caso de que el usuario introduzca un caracter 
no numérico, se captura la excepción y se muestra 
un mensaje indicando que debe ingresar un número válido.
'''

try:
    edad = int(input("Por favor, introduce tu edad: "))  # Convertir a entero directamente
except ValueError:
    print("Por favor, introduce un número válido.")
else:
    # Condicionales para verificar la edad y mostrar el mensaje adecuado
    if edad < 0:
        print("Ingresaste un valor negativo, esto es incorrecto.")
    elif 0 <= edad < 18:
        print("Lo siento, no puedes entrar a la fiesta.")
    elif 18 <= edad <= 25:
        print("Puedes entrar a la fiesta, pero solo con una bebida sin alcohol.")
    elif 25 < edad <= 120:
        print("Puedes entrar a la fiesta y te ofrecemos una bebida alcohólica.")
    else:
        print("Ingresaste un valor mayor que 120, esto es incorrecto.")


## Ejercicio 2: Transformar frases

Crea un código que tome la frase inicial entregada y la corrija de tal forma que quede igual a la frase final entregada. Donde:

* Frase inicial es "hola, soMos el mejor cursó de de Data-Science de Coding_Dojo. yahoo!!!"
* Frase final es "Hola, somos el mejor curso de Data Science de Coding Dojo"

### Soluciones posibles:


Solución 1:

1. Apicar una función que pase a todo a minúscula
2. En los casos particulares aplicamos mayúsculas
2. Reemplaza los "-" y "_" por espacios en blanco
3. Eliminamos todos los acentos
4. Elimine si tengo palabras duplicadas de foma consecutiva
5. Eliminar todo lo que viene después del punto o de la palabra Dojo

In [3]:
import unicodedata

# 1. Función para convertir a minúsculas
def convertir_minusculas(frase):
    return frase.lower()

# 2. Función para capitalizar casos particulares
def capitalizar_palabras_clave(frase):
    frase = frase.replace("data science", "Data Science")
    frase = frase.replace("coding dojo", "Coding Dojo")
    frase = frase.replace("de de", "de")
    return frase

# 3. Función para reemplazar "-" y "_" por espacios
def reemplazar_guiones(frase):
    frase = frase.replace("-", " ").replace("_", " ")
    return frase

# 4. Función para eliminar acentos
def eliminar_acentos(frase):
    # Utilizamos unicodedata para eliminar acentos
    nfkd_form = unicodedata.normalize('NFKD', frase)
    return "".join([c for c in nfkd_form if not unicodedata.combining(c)])

# 5. Función para eliminar todo lo que viene después de un punto o de la palabra "Dojo"
def eliminar_despues_de_punto_o_dojo(frase):
    # Encontrar el punto o la palabra "Dojo"
    indice_punto = frase.find(".")
    indice_dojo = frase.find("Dojo")
    
    # Determinar cuál índice usar
    if indice_dojo != -1:
        return frase[:indice_dojo + len("Dojo")].strip()
    elif indice_punto != -1:
        return frase[:indice_punto].strip()
    else:
        return frase.strip()

# Función principal que aplica todas las transformaciones
def transformar_frase(frase_inicial):
    frase = convertir_minusculas(frase_inicial)
    frase = reemplazar_guiones(frase)
    frase = eliminar_acentos(frase)
    frase = eliminar_despues_de_punto_o_dojo(frase)
    frase = capitalizar_palabras_clave(frase)
    return frase

### Solución Propuesta para el Ejercicio 2

1. Se importa la libreria 're' que proporciona funciones para trabajar con expresiones regulares, utilizado para búsqueda, coincidencia y manipulación de patrones en cadenas de texto.

2. Se define la función transformar_frase(), que toma por entrada dos argumentos: una frase inicial y una frase final esperada. El objetivo es transformar la frase inicial para que coincida lo más posible con la frase final, aplicando una serie de reglas.

3. Se imprimen la frase inicial y la frase final esperada, para visualizar el punto de partida del proceso y a dónde va orientado el proceso de transformación.

4. Se normalizan: los espacios múltiples y mal ubiucados, los caracteres alfabéticos innecesarios, las mayúsculas.

5. Se eliminan palabras duplicadas.

6. Se corrigen términos específicos.

9. Se eliminan palabras no deseadas.

10. Se corrige el acento.

11. Se capitalizan las palabras de acuerdo a la frase final.

12. Se asergura que se mantenga la primera coma.

13. Se reconstruye la frase transformada.

14. Se verifica si la frase transformada coincide con la frase final.

15. Se solicita el input del usuario.

16. Se llama a la función transformar_frase().


**Obs.:** Tal vez sea innecesariamente complicada, pero mi visión era definir una función que pudiera tener un uso más generalizado, que finalmente no se cumple ya que tuve que proporcionar reglas algo "arbitrarias", específicas para la corrección de esta frase en particular.
Pero, técnicamente, cumple con la premisa del ejercicio.

In [7]:
import re

def transformar_frase(frase_inicial, frase_final):
    # Mostrar las frases inicial y final
    print(f"\nFrase inicial: {frase_inicial}")
    print(f"Frase final esperada: {frase_final}\n")

    # 1. Normalizar espacios múltiples a un solo espacio y eliminar espacios al inicio y al final
    frase_inicial = re.sub(' +', ' ', frase_inicial.strip())
    
    # 2. Eliminar caracteres no alfabéticos innecesarios (excepto guiones y subrayados)
    frase_inicial = re.sub(r'[^\w\s,-]', '', frase_inicial)

    # 3. Normalizar a minúsculas
    frase_inicial = frase_inicial.lower()

    # 4. Corregir duplicados de palabras
    palabras = frase_inicial.split()
    palabras_unicas = []
    for palabra in palabras:
        if len(palabras_unicas) == 0 or palabras_unicas[-1] != palabra:
            palabras_unicas.append(palabra)
    frase_inicial = " ".join(palabras_unicas)

    # 5. Corregir términos específicos
    frase_inicial = frase_inicial.replace("data-science", "Data Science")
    frase_inicial = frase_inicial.replace("coding_dojo", "Coding Dojo")
    
    # 6. Eliminar palabras no deseadas como "Yahoo" (si no aparece en la frase final)
    frase_inicial = frase_inicial.replace("yahoo", "").strip()

    # 7. Reemplazar "cursó" por "curso" antes de capitalizar
    frase_inicial = frase_inicial.replace("cursó", "curso")

    # 8. Capitalizar correctamente las palabras que deben estar en mayúsculas según la frase final
    palabras_final = frase_final.split()
    palabras_inicial = frase_inicial.split()

    # Ajuste de capitalización
    for i in range(min(len(palabras_inicial), len(palabras_final))):
        if palabras_final[i].istitle():  # Si la palabra en la frase final está en mayúscula
            palabras_inicial[i] = palabras_inicial[i].capitalize()

    # 9. Asegurar que la coma después de "Hola" esté presente si aparece en la frase final
    if "hola," in frase_final.lower():
        palabras_inicial[0] = "Hola,"

    # Reconstruir la frase transformada
    frase_inicial = " ".join(palabras_inicial)

    # Mostrar el resultado
    print(f"Frase transformada: {frase_inicial}")

    # Comprobar si la transformación es correcta
    if frase_inicial == frase_final:
        print("La frase fue transformada correctamente.")
    else:
        print(f"La frase no coincide con la esperada.\nFrase final obtenida: {frase_inicial}\n")
        diferencias = [(f_in, f_fin) for f_in, f_fin in zip(palabras_inicial, palabras_final) if f_in != f_fin]
        print(f"Diferencias encontradas: {diferencias}")
    
# Solicitar input del usuario
frase_inicial_input = input("Ingresa la frase inicial: ")
frase_final_input = input("Ingresa la frase final esperada: ")

# Llamar a la función
transformar_frase(frase_inicial_input, frase_final_input)



Frase inicial: hola, soMos el mejor cursó de de Data-Science de Coding_Dojo. yahoo!!!
Frase final esperada: Hola, somos el mejor curso de Data Science de Coding Dojo

Frase transformada: Hola, somos el mejor curso de Data Science de Coding Dojo
La frase fue transformada correctamente.


### Solución Alternativa para el Ejercicio 2

Más sencilla, legible, menos flexible a otros errores ortográficos.

1. Imprimir la frase inicial.

2. Eliminar todo después del punto: Si la frase tiene un punto, se elimina todo lo que esté después del primer punto.

3. Eliminar espacios adicionales: Si hay espacios extra entre palabras, se reducen a un solo espacio.

4. Eliminar caracteres no deseados: Quitamos cualquier signo de puntuación o símbolo, excepto comas, letras, números y guiones.

5. Convertir a minúsculas: Convertimos toda la frase a minúsculas para facilitar la comparación y transformación.

6. Eliminar palabras duplicadas consecutivas: Si una palabra se repite inmediatamente, como "de de", eliminamos la repetición.

7. Corregir términos específicos: Arreglamos palabras o expresiones como "data-science", transformándolas en "Data Science", o "Coding_Dojo" a "Coding Dojo".

8. Corregir errores ortográficos: Cambiamos errores ortográficos conocidos, como "cursó" a "curso".

9. Capitalizar palabras importantes: Ponemos en mayúscula las palabras clave o nombres propios, como "Hola" o "Data Science". 

10. Reconstruir la frase final.

11. Comprobar el resultado.

In [24]:
import re

def transformar_frase(frase_inicial):
    # Imprimir la frase inicial
    print(f"Frase inicial: {frase_inicial}")
    
    # 1. Eliminar todo lo que sigue después del primer punto
    frase_inicial = re.split(r'\.', frase_inicial)[0]
    
    # 2. Normalizar espacios y mantener comas (eliminar otros caracteres no deseados)
    frase_inicial = re.sub(r'\s+', ' ', frase_inicial.strip())  # Eliminar espacios adicionales
    frase_inicial = re.sub(r'[^\w\s,-]', '', frase_inicial)  # Mantener comas y eliminar otros caracteres

    # 3. Convertir todo a minúsculas para homogeneizar
    frase_inicial = frase_inicial.lower()

    # 4. Corregir duplicación de palabras (como "de de")
    frase_inicial = re.sub(r'\b(\w+)\s+\1\b', r'\1', frase_inicial)

    # 5. Corregir palabras específicas con formato incorrecto
    frase_inicial = frase_inicial.replace("data-science", "Data Science")  # Corregir "Data Science"
    frase_inicial = frase_inicial.replace("coding_dojo", "Coding Dojo")  # Corregir "Coding Dojo"

    # 6. Corregir errores ortográficos o gramaticales
    frase_inicial = frase_inicial.replace("cursó", "curso")  # Cambiar "cursó" por "curso"

    # 7. Ajustar capitalización de las palabras al principio de la oración y otras palabras importantes
    palabras = frase_inicial.split()
    palabras[0] = palabras[0].capitalize()  # Capitalizar la primera palabra
    for i in range(len(palabras)):
        if palabras[i] in ["data", "science", "coding", "dojo"]:  # Capitalizar palabras clave
            palabras[i] = palabras[i].capitalize()

    # Reconstruir la frase final
    frase_final = " ".join(palabras)
    
    # Resultado final esperado
    return frase_final

# Frase inicial para probar
frase_inicial = "hola, soMos el mejor cursó de de Data-Science de Coding_Dojo. yahoo!!!"
# Frase final esperada
frase_final_esperada = "Hola, somos el mejor curso de Data Science de Coding Dojo"

# Llamar a la función y mostrar el resultado final exacto
frase_final_corregida = transformar_frase(frase_inicial)
print(f"Frase final corregida: {frase_final_corregida}")

# Comprobación
if frase_final_corregida == frase_final_esperada:
    print("La frase corregida coincide con la frase final esperada.")
else:
    print(f"La frase corregida no coincide con la frase final esperada. \nFrase corregida: {frase_final_corregida}")

Frase inicial: hola, soMos el mejor cursó de de Data-Science de Coding_Dojo. yahoo!!!
Frase final corregida: Hola, somos el mejor curso de Data Science de Coding Dojo
La frase corregida coincide con la frase final esperada.


## Ejercicio 3 : Verificar la contraseña de un usuario

**Descripción:** El programa debe pedir al usuario un nombre y una contraseña. Después de eso, verificará si la contraseña ingresada cumple con ciertos criterios:

* La contraseña debe tener al menos 8 caracteres.
* Debe contener al menos una letra mayúscula.
* Debe contener al menos un número.
* Si la contraseña cumple con todos los criterios, el programa dirá que el registro fue exitoso; si no, indicará qué condición no se cumplió y pedirá al usuario que lo intente nuevamente.

**Objetivos:**

* Repasar cómo definir y usar funciones.
* Manejar input y output de manera dinámica.
* Usar condicionales para verificar múltiples criterios.
* Manipular cadenas de texto (uso de métodos como .isupper(), .isdigit(), etc.).

### Lógica a seguir
**1. Solicitar el nombre del usuario:**

El código comienza pidiendo al usuario que introduzca su nombre. Esto se guarda para luego mostrar un mensaje de éxito cuando la contraseña sea válida.

**2. Solicitar la contraseña:**

En cada iteración, el código solicita al usuario que ingrese una contraseña. Este proceso continúa hasta que la contraseña sea válida.

**3. Verificación de la longitud de la contraseña:**

La primera condición que se verifica es si la contraseña tiene al menos 8 caracteres. Si la longitud es inferior, se muestra un mensaje informando al usuario de este error y se le pide que lo intente nuevamente.

**4. Verificación de letras mayúsculas:**

Si la contraseña tiene la longitud adecuada, el siguiente paso es comprobar si contiene al menos una letra mayúscula. Si no la contiene, el usuario recibe un mensaje indicando la falta de una letra mayúscula y se le pide que lo intente de nuevo.

**5. Verificación de números:**

Si la contraseña tiene al menos una letra mayúscula, el código procede a verificar si contiene al menos un número. Si no se encuentra un número, el usuario es informado y se le solicita que ingrese una nueva contraseña.

**6. Mensajes de error por cada verificación fallida:**

Por cada verificación fallida (longitud, mayúsculas o números), se muestra un mensaje de error específico. Tras cada mensaje de error, el programa solicita una nueva contraseña.

**7. Registro exitoso:**

Una vez que la contraseña cumple con todos los requisitos (longitud, mayúsculas y números), el código muestra un mensaje de "Registro exitoso" utilizando el nombre que el usuario introdujo al inicio.

In [6]:
def verificar_contraseña(contraseña):
    # Verificar si la longitud es al menos 8 caracteres
    if len(contraseña) < 8:
        print("La contraseña debe tener al menos 8 caracteres.")
        return False
    
    # Verificar si contiene al menos una letra mayúscula
    if not any(letra.isupper() for letra in contraseña):
        print("La contraseña debe contener al menos una letra mayúscula.")
        return False
    
    # Verificar si contiene al menos un número
    if not any(letra.isdigit() for letra in contraseña):
        print("La contraseña debe contener al menos un número.")
        return False
    
    # Si cumple con todos los criterios
    return True

def solicitar_datos_usuario():
    nombre = input("Por favor, introduce tu nombre: ")
    contraseña_valida = False
    
    while not contraseña_valida:
        contraseña = input("Introduce tu contraseña: ")
        # Solo llamar a verificar_contraseña una vez por ciclo
        contraseña_valida = verificar_contraseña(contraseña)
        if not contraseña_valida:
            print("Por favor, intenta nuevamente.")
    
    # Si la contraseña es válida, mostrar mensaje de registro exitoso
    print(f"Registro exitoso, {nombre}!")

# Iniciar el proceso de registro
solicitar_datos_usuario()

''' 
Para demostrar que el código funciona correctamente, 
se usaron una serie de entradas para verificar cada condición. 
Cuando se ingresa una contraseña demasiado corta (`abcD1`), 
el código muestra un mensaje de error indicando 
que debe tener al menos 8 caracteres. 
Si se proporciona una contraseña que no tiene mayúsculas (`abcd1234`), 
el sistema indica que debe incluir al menos una. 
Si no contiene un número (`Abcdefgh`), se informa que debe agregar uno. 
Finalmente, cuando se ingresa una contraseña válida (`Abcdefg1`), 
el registro es exitoso y se muestra un mensaje de confirmación.

'''

La contraseña debe tener al menos 8 caracteres.
Por favor, intenta nuevamente.
La contraseña debe contener al menos una letra mayúscula.
Por favor, intenta nuevamente.
La contraseña debe contener al menos un número.
Por favor, intenta nuevamente.
Registro exitoso, Andrea!


## Ejercicio 4: Análisis de Calificaciones de Estudiantes

**Descripción del problema** Supongamos que tenemos las calificaciones de un grupo de estudiantes en 3 materias: Matemáticas, Ciencias y Lenguaje. Queremos realizar varias operaciones utilizando arrays para analizar las calificaciones y calcular estadísticas.

**Instrucciones:**

* Creación de arrays: Crea un array bidimensional donde cada fila represente un estudiante y cada columna las calificaciones en Matemáticas, Ciencias y Lenguaje.
* Propiedades y Métodos: Imprime las propiedades del array, como su forma (shape), número de elementos (size) y tipo de datos (dtype).
* Operaciones básicas: Calcula la calificación promedio por materia y por estudiante.
* Multiplicación y división: Multiplica las calificaciones de todos los estudiantes por 1.1 (simulando una mejora del 10% en todas las calificaciones) y divide las calificaciones de Ciencias por 2 (simulando que el peso de Ciencias es la mitad que el de otras materias).
* Operaciones universales (ufuncs): Aplica una función universal (ufunc) como la raíz cuadrada de las calificaciones mejoradas.
* Indexación y slicing: Extrae las calificaciones de Matemáticas de todos los estudiantes.
* Suma y producto: Calcula la suma total y el producto de las calificaciones por estudiante.
* Estadísticas básicas: Calcula el promedio, la desviación estándar y el máximo de las calificaciones en cada materia.
* Agregaciones en arrays multidimensionales: Calcula la suma de las calificaciones por materia.

In [7]:
import numpy as np

# 1. Creación de un array bidimensional con las calificaciones de los estudiantes
calificaciones = np.array([
    [60, 70, 85],  # Estudiante 1: Matemáticas, Ciencias, Lenguaje
    [78, 88, 91],  # Estudiante 2
    [92, 90, 95],  # Estudiante 3
    [85, 80, 88],  # Estudiante 4
    [75, 82, 70]   # Estudiante 5
])

# 2. Propiedades del array
print("Propiedades del array:")
print(f"Forma (shape): {calificaciones.shape}")
print(f"Número de elementos (size): {calificaciones.size}")
print(f"Tipo de datos (dtype): {calificaciones.dtype}")
print("\n")

Propiedades del array:
Forma (shape): (5, 3)
Número de elementos (size): 15
Tipo de datos (dtype): int64




In [9]:
# 3. Operaciones básicas
print("Operaciones básicas:")
suma_total = np.mean(calificaciones, axis=0)
promedio_estudiante = np.mean(calificaciones, axis=1)
print(f"Suma total de las calificaciones: {suma_total}")
print(f"Promedio de calificaciones por estudiante: {promedio_estudiante}")
print("\n")


Operaciones básicas:
Suma total de las calificaciones: [78.  82.  85.8]
Promedio de calificaciones por estudiante: [71.66666667 85.66666667 92.33333333 84.33333333 75.66666667]




In [10]:
# 4. Multiplicación y división
print("Multiplicación y división:")
mejora_10_por_ciento = calificaciones * 1.1  # Mejora del 10% en todas las calificaciones
#mejora_10_por_ciento_alumno_1 = calificaciones[0,0:] * 1.1 
calificaciones_ciencias_mitad = calificaciones[:, 1] / 2  # División de Ciencias por 2
#calificaciones_ciencias_mitad = calificaciones[:, 1:3] / 2  # División de Ciencias y lenguaje por 2
print(f"Calificaciones mejoradas (10%): \n{mejora_10_por_ciento}")
print(f"Calificaciones de Ciencias divididas por 2: {calificaciones_ciencias_mitad}")
print("\n")

Multiplicación y división:
Calificaciones mejoradas (10%): 
[[ 66.   77.   93.5]
 [ 85.8  96.8 100.1]
 [101.2  99.  104.5]
 [ 93.5  88.   96.8]
 [ 82.5  90.2  77. ]]
Calificaciones de Ciencias divididas por 2: [35. 44. 45. 40. 41.]




In [11]:
# 5. Operaciones universales (ufuncs)
print("Operaciones universales (ufuncs):")
raiz_calificaciones_mejoradas = np.sqrt(mejora_10_por_ciento)
print(f"Raíz cuadrada de las calificaciones mejoradas: \n{raiz_calificaciones_mejoradas}")
print("\n")

Operaciones universales (ufuncs):
Raíz cuadrada de las calificaciones mejoradas: 
[[ 8.1240384   8.77496439  9.6695398 ]
 [ 9.26282894  9.8386991  10.00499875]
 [10.05982107  9.94987437 10.22252415]
 [ 9.6695398   9.38083152  9.8386991 ]
 [ 9.08295106  9.49736806  8.77496439]]




In [12]:
# 6. Indexación y slicing
print("Indexación y slicing:")
calificaciones_matematicas = calificaciones[:, 0]  # Extraer las calificaciones de Matemáticas
print(f"Calificaciones en Matemáticas de todos los estudiantes: {calificaciones_matematicas}")
print("\n")

Indexación y slicing:
Calificaciones en Matemáticas de todos los estudiantes: [60 78 92 85 75]




In [13]:
# 7. Suma y producto
print("Suma y producto:")
suma_por_estudiante = np.sum(calificaciones, axis=1)
producto_por_estudiante = np.prod(calificaciones, axis=1)
print(f"Suma total de calificaciones por estudiante: {suma_por_estudiante}")
print(f"Producto de calificaciones por estudiante: {producto_por_estudiante}")
print("\n")

Suma y producto:
Suma total de calificaciones por estudiante: [215 257 277 253 227]
Producto de calificaciones por estudiante: [357000 624624 786600 598400 430500]




In [14]:
# 8. Estadísticas básicas
print("Estadísticas básicas:")
promedio_materias = np.mean(calificaciones, axis=0)
desviacion_estandar_materias = np.std(calificaciones, axis=0)
minima_materias = np.min(calificaciones, axis=0)
maximo_materias = np.max(calificaciones, axis=0)
coeficiente_variacion = 100 * desviacion_estandar_materias/promedio_materias
print(f"Promedio de calificaciones por materia: {promedio_materias}")
print(f"Desviación estándar por materia: {desviacion_estandar_materias}")
print(f"Calificación mínima por materia: {minima_materias}")
print(f"Calificación máxima por materia: {maximo_materias}")
print(f"Calificación máxima por materia: {coeficiente_variacion}")
print("\n")

Estadísticas básicas:
Promedio de calificaciones por materia: [78.  82.  85.8]
Desviación estándar por materia: [10.75174404  7.04272674  8.56504524]
Calificación mínima por materia: [60 70 70]
Calificación máxima por materia: [92 90 95]
Calificación máxima por materia: [13.78428724  8.58869115  9.98257021]




In [15]:
# 9. Agregaciones en arrays multidimensionales
print("Agregaciones en arrays multidimensionales:")
suma_por_materia = np.sum(calificaciones, axis=0)
print(f"Suma total de calificaciones por materia: {suma_por_materia}")

Agregaciones en arrays multidimensionales:
Suma total de calificaciones por materia: [390 410 429]


### Calcular percentil 25, 50, 75 sobre el arreglo de calificaciones:

1. Para cada estudiante
2. Para cada materia

In [16]:

# Calcular percentiles 25, 50 y 75 para cada estudiante (axis 1)
percentiles_estudiantes = np.percentile(calificaciones, [25, 50, 75], axis=1)

# Calcular percentiles 25, 50 y 75 para cada materia (axis 0)
percentiles_materias = np.percentile(calificaciones, [25, 50, 75], axis=0)

# Mostrar los resultados
print("Percentiles 25, 50, 75 para cada estudiante:\n", percentiles_estudiantes)
print("\nPercentiles 25, 50, 75 para cada materia:\n", percentiles_materias)


Percentiles 25, 50, 75 para cada estudiante:
 [[65.  83.  91.  82.5 72.5]
 [70.  88.  92.  85.  75. ]
 [77.5 89.5 93.5 86.5 78.5]]

Percentiles 25, 50, 75 para cada materia:
 [[75. 80. 85.]
 [78. 82. 88.]
 [85. 88. 91.]]
