### Ejercicio 1: Verificar la edad para entrar en una fiesta

Descripción: El programa debe solicitar al usuario su edad y, en función de la misma, mostrar un mensaje indicando si puede entrar a una fiesta. Las reglas son las siguientes:

* Si el usuario tiene menos de 18 años, se mostrará un mensaje diciendo que no puede entrar.
* Si el usuario tiene entre 18 y 25 años (inclusive), se le permitirá entrar con una bebida sin alcohol.
* Si el usuario tiene más de 25 años, se le permitirá entrar con una bebida alcohólica.

**Objetivo**

* Repasar cómo tomar input del usuario.
* Usar condicionales para determinar la salida.
* Mostrar mensajes usando output.

Tareas:

1. Tengo que generar un mecanismo por el cual pueda ingresar un valor
2. Asignar el valor ingresado a una variable y ser capaz de identificar cuál de las 3 condiciones se cumple
3. Entregar como output el valor correspondiente a la condición cumplida

In [2]:
# Pedir la edad al usuario
edad = input("Por favor, introduce tu edad: ")
if type(edad) == str:
    edad = int(edad)

# Condicionales para verificar la edad y mostrar el mensaje adecuado
if edad < 0:
    print("ingresaste un valor negativo, esto es incorrecto")
elif 0 <= edad < 18:
    print("Lo siento, no puedes entrar a la fiesta.")
elif 18 <= edad <= 25:
    print("Puedes entrar a la fiesta, pero solo con una bebida sin alcohol.")
elif 25 < edad < 140:
    print("Puedes entrar a la fiesta y te ofrecemos una bebida alcohólica.")
else:
    print("ingresaste un valor mayor que 140, esto es incorrecto")


Lo siento, no puedes entrar a la fiesta.


### Ejercicio 2: Transformar frases

Crea un código que tome la frase inicial entregada y la corrija de tal forma que quede igual a la frase final entregada. Donde:

* frase inicial es "hola, soMos el mejor cursó de de Data-Science de Coding_Dojo. yahoo!!!"
* frase final es "hola, somos el mejor curso de Data Science de Coding Dojo"

soluciones posibles:

Solución 1:

1. Apicar una función que pase a todo a minúscula
2. En los casos particulares aplicamos mayúsculas
2. Reemplaza los "-" y "_" por espacios en blanco
3. Eliminamos todos los acentos
4. Elimine si tengo palabras duplicadas de foma consecutiva
5. Eliminar todo lo que viene después del punto o de la palabra Dojo

In [3]:
import unicodedata

# 1. Función para convertir a minúsculas
def convertir_minusculas(frase):
    return frase.lower()

# 2. Función para capitalizar casos particulares
def capitalizar_palabras_clave(frase):
    frase = frase.replace("data science", "Data Science")
    frase = frase.replace("coding dojo", "Coding Dojo")
    frase = frase.replace("de de", "de")
    return frase

# 3. Función para reemplazar "-" y "_" por espacios
def reemplazar_guiones(frase):
    frase = frase.replace("-", " ").replace("_", " ")
    return frase

# 4. Función para eliminar acentos
def eliminar_acentos(frase):
    # Utilizamos unicodedata para eliminar acentos
    nfkd_form = unicodedata.normalize('NFKD', frase)
    return "".join([c for c in nfkd_form if not unicodedata.combining(c)])

# 5. Función para eliminar todo lo que viene después de un punto o de la palabra "Dojo"
def eliminar_despues_de_punto_o_dojo(frase):
    # Encontrar el punto o la palabra "Dojo"
    indice_punto = frase.find(".")
    indice_dojo = frase.find("Dojo")
    
    # Determinar cuál índice usar
    if indice_dojo != -1:
        return frase[:indice_dojo + len("Dojo")].strip()
    elif indice_punto != -1:
        return frase[:indice_punto].strip()
    else:
        return frase.strip()

# Función principal que aplica todas las transformaciones
def transformar_frase(frase_inicial):
    frase = convertir_minusculas(frase_inicial)
    frase = reemplazar_guiones(frase)
    frase = eliminar_acentos(frase)
    frase = eliminar_despues_de_punto_o_dojo(frase)
    frase = capitalizar_palabras_clave(frase)
    return frase

In [4]:
# Ejemplo de uso
frase_inicial = "hola, soMos el mejor cursó de de Data-Science de Coding_Dojo. yahoo!!!"
frase_final = transformar_frase(frase_inicial)
frase_final

'hola, somos el mejor curso de Data Science de Coding Dojo'

## Ejercicio 3 : Verificar la contraseña de un usuario

Descripción: El programa debe pedir al usuario un nombre y una contraseña. Después de eso, verificará si la contraseña ingresada cumple con ciertos criterios:

* La contraseña debe tener al menos 8 caracteres.
* Debe contener al menos una letra mayúscula.
* Debe contener al menos un número.
* Si la contraseña cumple con todos los criterios, el programa dirá que el registro fue exitoso; si no, indicará qué condición no se cumplió y pedirá al usuario que lo intente nuevamente.

Objetivos:

* Repasar cómo definir y usar funciones.
* Manejar input y output de manera dinámica.
* Usar condicionales para verificar múltiples criterios.
* Manipular cadenas de texto (uso de métodos como .isupper(), .isdigit(), etc.).

Ejercicio: Análisis de Calificaciones de Estudiantes

**Descripción del problema** Supongamos que tenemos las calificaciones de un grupo de estudiantes en 3 materias: Matemáticas, Ciencias y Lenguaje. Queremos realizar varias operaciones utilizando arrays para analizar las calificaciones y calcular estadísticas.

**Instrucciones:**

* Creación de arrays: Crea un array bidimensional donde cada fila represente un estudiante y cada columna las calificaciones en Matemáticas, Ciencias y Lenguaje.
* Propiedades y Métodos: Imprime las propiedades del array, como su forma (shape), número de elementos (size) y tipo de datos (dtype).
* Operaciones básicas: Calcula la calificación promedio por materia y por estudiante.
* Multiplicación y división: Multiplica las calificaciones de todos los estudiantes por 1.1 (simulando una mejora del 10% en todas las calificaciones) y divide las calificaciones de Ciencias por 2 (simulando que el peso de Ciencias es la mitad que el de otras materias).
* Operaciones universales (ufuncs): Aplica una función universal (ufunc) como la raíz cuadrada de las calificaciones mejoradas.
* Indexación y slicing: Extrae las calificaciones de Matemáticas de todos los estudiantes.
* Suma y producto: Calcula la suma total y el producto de las calificaciones por estudiante.
* Estadísticas básicas: Calcula el promedio, la desviación estándar y el máximo de las calificaciones en cada materia.
* Agregaciones en arrays multidimensionales: Calcula la suma de las calificaciones por materia.

In [31]:
import numpy as np

# 1. Creación de un array bidimensional con las calificaciones de los estudiantes
calificaciones = np.array([
    [40, 55, 28],  # Estudiante 1: Matemáticas, Ciencias, Lenguaje
    [68, 52, 80],  # Estudiante 2
    [92, 95, 85],  # Estudiante 3
    [75, 75, 78],  # Estudiante 4
    [20, 17, 10],  # Estudiante 5
])

# 2. Propiedades del array
print("Propiedades del array:")
print(f"Forma (shape): {calificaciones.shape}")
print(f"Número de elementos (size): {calificaciones.size}")
print(f"Tipo de datos (dtype): {calificaciones.dtype}")
print("\n")

Propiedades del array:
Forma (shape): (5, 3)
Número de elementos (size): 15
Tipo de datos (dtype): int64




In [32]:
calificaciones[0:,1:]

array([[55, 28],
       [52, 80],
       [95, 85],
       [75, 78],
       [17, 10]])

In [33]:
# 3. Operaciones básicas
print("Operaciones básicas:")
suma_total = np.mean(calificaciones, axis=0)
promedio_estudiante = np.mean(calificaciones, axis=1)
print(f"Suma total de las calificaciones: {suma_total}")
print(f"Promedio de calificaciones por estudiante: {promedio_estudiante}")
print("\n")


Operaciones básicas:
Suma total de las calificaciones: [59.  58.8 56.2]
Promedio de calificaciones por estudiante: [41.         66.66666667 90.66666667 76.         15.66666667]




In [34]:
# 4. Multiplicación y división
print("Multiplicación y división:")
mejora_10_por_ciento = calificaciones * 1.1  # Mejora del 10% en todas las calificaciones
#mejora_10_por_ciento_alumno_1 = calificaciones[0,0:] * 1.1 
calificaciones_ciencias_mitad = calificaciones[:, 1] / 2  # División de Ciencias por 2
#calificaciones_ciencias_mitad = calificaciones[:, 1:3] / 2  # División de Ciencias y lenguaje por 2
print(f"Calificaciones mejoradas (10%): \n{mejora_10_por_ciento}")
print(f"Calificaciones de Ciencias divididas por 2: {calificaciones_ciencias_mitad}")
print("\n")

Multiplicación y división:
Calificaciones mejoradas (10%): 
[[ 44.   60.5  30.8]
 [ 74.8  57.2  88. ]
 [101.2 104.5  93.5]
 [ 82.5  82.5  85.8]
 [ 22.   18.7  11. ]]
Calificaciones de Ciencias divididas por 2: [27.5 26.  47.5 37.5  8.5]




In [35]:
# 5. Operaciones universales (ufuncs)
print("Operaciones universales (ufuncs):")
raiz_calificaciones_mejoradas = np.sqrt(mejora_10_por_ciento)
print(f"Raíz cuadrada de las calificaciones mejoradas: \n{raiz_calificaciones_mejoradas}")
print("\n")

Operaciones universales (ufuncs):
Raíz cuadrada de las calificaciones mejoradas: 
[[ 6.63324958  7.77817459  5.54977477]
 [ 8.64869932  7.56306816  9.38083152]
 [10.05982107 10.22252415  9.6695398 ]
 [ 9.08295106  9.08295106  9.26282894]
 [ 4.69041576  4.32434966  3.31662479]]




In [36]:
# 6. Indexación y slicing
print("Indexación y slicing:")
calificaciones_matematicas = calificaciones[:, 0]  # Extraer las calificaciones de Matemáticas
print(f"Calificaciones en Matemáticas de todos los estudiantes: {calificaciones_matematicas}")
print("\n")

Indexación y slicing:
Calificaciones en Matemáticas de todos los estudiantes: [40 68 92 75 20]




In [37]:
# 7. Suma y producto
print("Suma y producto:")
suma_por_estudiante = np.sum(calificaciones, axis=1)
producto_por_estudiante = np.prod(calificaciones, axis=1)
print(f"Suma total de calificaciones por estudiante: {suma_por_estudiante}")
print(f"Producto de calificaciones por estudiante: {producto_por_estudiante}")
print("\n")

Suma y producto:
Suma total de calificaciones por estudiante: [123 200 272 228  47]
Producto de calificaciones por estudiante: [ 61600 282880 742900 438750   3400]




In [44]:
# 8. Estadísticas básicas
print("Estadísticas básicas:")
promedio_materias = np.mean(calificaciones, axis=0)
desviacion_estandar_materias = np.std(calificaciones, axis=0)
minima_materias = np.min(calificaciones, axis=0)
maximo_materias = np.max(calificaciones, axis=0)
coeficiente_variacion = 100 * desviacion_estandar_materias/promedio_materias
print(f"Promedio de calificaciones por materia: {promedio_materias}")
print(f"Desviación estándar por materia: {desviacion_estandar_materias}")
print(f"Calificación mínima por materia: {minima_materias}")
print(f"Calificación máxima por materia: {maximo_materias}")
print(f"Calificación máxima por materia: {coeficiente_variacion}")
print("\n")

Estadísticas básicas:
Promedio de calificaciones por materia: [59.  58.8 56.2]
Desviación estándar por materia: [25.72158627 26.00307674 30.98644865]
Calificación mínima por materia: [20 17 10]
Calificación máxima por materia: [92 95 85]
Calificación máxima por materia: [43.59590892 44.22291963 55.13602963]




In [43]:
# 9. Agregaciones en arrays multidimensionales
print("Agregaciones en arrays multidimensionales:")
suma_por_materia = np.sum(calificaciones, axis=0)
print(f"Suma total de calificaciones por materia: {suma_por_materia}")

Agregaciones en arrays multidimensionales:
Suma total de calificaciones por materia: [295 294 281]


Calcular percentil 25, 50, 75 sobre el arreglo de calificaciones:

1. Para cada estudiante
2. Para cada materia

In [1]:
import numpy as np

# 1. Creación del array bidimensional con las calificaciones de los estudiantes
calificaciones = np.array([
    [40, 55, 28],  # Estudiante 1: Matemáticas, Ciencias, Lenguaje
    [68, 52, 80],  # Estudiante 2
    [92, 95, 85],  # Estudiante 3
    [75, 75, 78],  # Estudiante 4
    [20, 17, 10],  # Estudiante 5
])

# 2. Calcular los percentiles 25, 50 y 75 para cada estudiante
print("Percentiles por estudiante:")
for i, estudiante in enumerate(calificaciones):
    p25 = np.percentile(estudiante, 25)
    p50 = np.percentile(estudiante, 50)
    p75 = np.percentile(estudiante, 75)
    print(f"Estudiante {i+1}: Percentil 25 = {p25}, Percentil 50 = {p50}, Percentil 75 = {p75}")

# 3. Calcular los percentiles 25, 50 y 75 para cada materia (columna)
print("\nPercentiles por materia:")
materias = ['Matemáticas', 'Ciencias', 'Lenguaje']
for i in range(calificaciones.shape[1]):  # Iterar sobre las columnas (materias)
    materia = calificaciones[:, i]  # Seleccionar los datos de la materia
    p25 = np.percentile(materia, 25)
    p50 = np.percentile(materia, 50)
    p75 = np.percentile(materia, 75)
    print(f"{materias[i]}: Percentil 25 = {p25}, Percentil 50 = {p50}, Percentil 75 = {p75}")


Percentiles por estudiante:
Estudiante 1: Percentil 25 = 34.0, Percentil 50 = 40.0, Percentil 75 = 47.5
Estudiante 2: Percentil 25 = 60.0, Percentil 50 = 68.0, Percentil 75 = 74.0
Estudiante 3: Percentil 25 = 88.5, Percentil 50 = 92.0, Percentil 75 = 93.5
Estudiante 4: Percentil 25 = 75.0, Percentil 50 = 75.0, Percentil 75 = 76.5
Estudiante 5: Percentil 25 = 13.5, Percentil 50 = 17.0, Percentil 75 = 18.5

Percentiles por materia:
Matemáticas: Percentil 25 = 40.0, Percentil 50 = 68.0, Percentil 75 = 75.0
Ciencias: Percentil 25 = 52.0, Percentil 50 = 55.0, Percentil 75 = 75.0
Lenguaje: Percentil 25 = 28.0, Percentil 50 = 78.0, Percentil 75 = 80.0
